/home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxSATFormulaExtended.o /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxSATFormulaExtended.or /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxSATFormulaExtended.od /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxSATFormulaExtended.op: \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxSATFormulaExtended.cc \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxSATFormulaExtended.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxSATFormula.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/Solver.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Heap.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Vec.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/IntTypes.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/XAlloc.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Alg.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/utils/Options.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/utils/ParseUtils.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/SolverTypes.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Map.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Alloc.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/BoundedQueue.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/Constants.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Clone.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/SolverStats.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/FormulaPB.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxTypes.h
/home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxSAT.o /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxSAT.or /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxSAT.od /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxSAT.op: /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxSAT.cc \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxSAT.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/Solver.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Heap.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Vec.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/IntTypes.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/XAlloc.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Alg.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/utils/Options.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/utils/ParseUtils.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/SolverTypes.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Map.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Alloc.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/BoundedQueue.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/Constants.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Clone.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/SolverStats.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxSATFormula.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/FormulaPB.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxTypes.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/utils/System.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxSATFormulaExtended.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/Torc.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/Encoder.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/encodings/Enc_CNetworks.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/encodings/Encodings.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/encodings/../MaxTypes.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/encodings/Enc_GTE.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/encodings/Enc_GTECluster.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/encodings/Enc_GTE.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/encodings/Enc_GTEIncremental.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/encodings/Enc_Ladder.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/encodings/Enc_MTotalizer.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/encodings/Enc_SWC.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/encodings/Enc_Totalizer.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/encodings/Enc_Adder.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/algorithms/Alg_nuweighting.h
/home/chuyi/NuWLS-c-2023-support-warmstarting/code/Encoder.o /home/chuyi/NuWLS-c-2023-support-warmstarting/code/Encoder.or /home/chuyi/NuWLS-c-2023-support-warmstarting/code/Encoder.od /home/chuyi/NuWLS-c-2023-support-warmstarting/code/Encoder.op: /home/chuyi/NuWLS-c-2023-support-warmstarting/code/Encoder.cc \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/Encoder.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/Solver.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Heap.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Vec.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/IntTypes.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/XAlloc.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Alg.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/utils/Options.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/utils/ParseUtils.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/SolverTypes.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Map.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Alloc.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/BoundedQueue.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/Constants.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Clone.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/SolverStats.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxTypes.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/encodings/Enc_CNetworks.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/encodings/Encodings.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/encodings/../MaxTypes.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/encodings/Enc_GTE.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/encodings/Enc_GTECluster.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/encodings/Enc_GTE.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/encodings/Enc_GTEIncremental.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/encodings/Enc_Ladder.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/encodings/Enc_MTotalizer.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/encodings/Enc_SWC.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/encodings/Enc_Totalizer.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/encodings/Enc_Adder.h
/home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxSAT_Partition.o /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxSAT_Partition.or /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxSAT_Partition.od /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxSAT_Partition.op: \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxSAT_Partition.cc \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/SolverTypes.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/IntTypes.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Alg.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Vec.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/XAlloc.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Map.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Alloc.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxSAT_Partition.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxSAT.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/Solver.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Heap.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/utils/Options.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/utils/ParseUtils.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/BoundedQueue.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/Constants.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Clone.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/SolverStats.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxSATFormula.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/FormulaPB.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxTypes.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/utils/System.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxSATFormulaExtended.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/Torc.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/graph/Graph.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/graph/Graph_Communities.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/graph/Graph.h
/home/chuyi/NuWLS-c-2023-support-warmstarting/code/ParserPB.o /home/chuyi/NuWLS-c-2023-support-warmstarting/code/ParserPB.or /home/chuyi/NuWLS-c-2023-support-warmstarting/code/ParserPB.od /home/chuyi/NuWLS-c-2023-support-warmstarting/code/ParserPB.op: \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/ParserPB.cc \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/ParserPB.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxSATFormula.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/Solver.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Heap.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Vec.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/IntTypes.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/XAlloc.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Alg.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/utils/Options.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/utils/ParseUtils.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/SolverTypes.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Map.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Alloc.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/BoundedQueue.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/Constants.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Clone.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/SolverStats.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/FormulaPB.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxTypes.h
/home/chuyi/NuWLS-c-2023-support-warmstarting/code/Torc.o /home/chuyi/NuWLS-c-2023-support-warmstarting/code/Torc.or /home/chuyi/NuWLS-c-2023-support-warmstarting/code/Torc.od /home/chuyi/NuWLS-c-2023-support-warmstarting/code/Torc.op: /home/chuyi/NuWLS-c-2023-support-warmstarting/code/Torc.cc \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxSAT.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/Solver.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Heap.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Vec.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/IntTypes.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/XAlloc.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Alg.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/utils/Options.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/utils/ParseUtils.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/SolverTypes.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Map.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Alloc.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/BoundedQueue.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/Constants.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Clone.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/SolverStats.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxSATFormula.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/FormulaPB.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxTypes.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/utils/System.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxSATFormulaExtended.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/Torc.h
/home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxSATFormula.o /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxSATFormula.or /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxSATFormula.od /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxSATFormula.op: \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxSATFormula.cc \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxSATFormula.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/Solver.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Heap.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Vec.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/IntTypes.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/XAlloc.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Alg.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/utils/Options.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/utils/ParseUtils.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/SolverTypes.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Map.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Alloc.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/BoundedQueue.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/Constants.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Clone.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/SolverStats.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/FormulaPB.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxTypes.h
/home/chuyi/NuWLS-c-2023-support-warmstarting/code/Main.o /home/chuyi/NuWLS-c-2023-support-warmstarting/code/Main.or /home/chuyi/NuWLS-c-2023-support-warmstarting/code/Main.od /home/chuyi/NuWLS-c-2023-support-warmstarting/code/Main.op: /home/chuyi/NuWLS-c-2023-support-warmstarting/code/Main.cc \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/utils/Options.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/IntTypes.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Vec.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/XAlloc.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/utils/ParseUtils.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/utils/System.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/Solver.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Heap.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Alg.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/SolverTypes.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Map.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Alloc.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/BoundedQueue.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/Constants.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/mtl/Clone.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/solvers/glucose4.1/core/SolverStats.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxSAT.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxSATFormula.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/FormulaPB.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxTypes.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/MaxSATFormulaExtended.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/Torc.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/ParserMaxSAT.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/ParserPB.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/algorithms/Alg_LinearSU.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/algorithms/../Encoder.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/algorithms/../MaxTypes.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/algorithms/../encodings/Enc_CNetworks.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/algorithms/../encodings/Encodings.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/algorithms/../encodings/../MaxTypes.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/algorithms/../encodings/Enc_GTE.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/algorithms/../encodings/Enc_GTECluster.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/algorithms/../encodings/Enc_GTE.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/algorithms/../encodings/Enc_GTEIncremental.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/algorithms/../encodings/Enc_Ladder.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/algorithms/../encodings/Enc_MTotalizer.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/algorithms/../encodings/Enc_SWC.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/algorithms/../encodings/Enc_Totalizer.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/algorithms/../encodings/Enc_Adder.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/algorithms/../MaxSAT.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/algorithms/Alg_LinearSU_Clustering.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/algorithms/../MaxTypes.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/algorithms/../clusterings/Cluster.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/algorithms/../clusterings/../MaxSATFormulaExtended.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/algorithms/../clusterings/SequenceStatistic.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/algorithms/../clusterings/../MaxTypes.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/algorithms/../clusterings/Cluster_DivisiveMaxSeparate.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/algorithms/../clusterings/Cluster.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/algorithms/Alg_LinearSU_Mod.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/algorithms/Alg_MSU3.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/algorithms/Alg_OLL.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/algorithms/Alg_OLL_Mod.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/algorithms/Alg_PartMSU3.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/algorithms/../MaxSAT_Partition.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/algorithms/../MaxSAT.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/algorithms/../graph/Graph.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/algorithms/../graph/Graph_Communities.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/algorithms/../graph/Graph.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/algorithms/Alg_WBO.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/algorithms/Alg_OBV.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/algorithms/Alg_BLS.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/Test.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/encodings/Enc_GTECluster.h \
 /home/chuyi/NuWLS-c-2023-support-warmstarting/code/encodings/Enc_GTEIncremental.h
